#!/usr/bin/env bash
exec clang++ \
  --target=i386-unknown-none-elf \
  -ffreestanding \
  -fno-builtin \
  -fno-exceptions \
  -fno-rtti \
  -fno-stack-protector \
  -fno-pic \
  -m32 \
  -march=i486 \
  -mno-sse \
  -mno-mmx \
  -mno-80387 \
  -nostdinc++ \
  -Wall -Wextra \
  -O2 \
  "$@"
